name: RELEASE
on: [workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint affected
        run: npx nx run-many -t lint
      - name: Test affected
        run: npx nx run-many -t test --configuration=ci
      - name: Build affected
        run: npx nx run-many -t build
      - name: Release
        run: npx nx run-many -t release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
